{{- if .Values.acr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.acr.secretName }}
  namespace: {{ .Values.namespaces.devops }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"none\"}}}" .Values.acr.dockerServer .Values.acr.dockerUsername .Values.acr.dockerPassword | b64enc }}
{{- end }}
