apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.tokenSecretName }}
  namespace: {{ .Values.namespaces.azureagents }}
type: Opaque
data:
  token: {{ .Values.agent.token | b64enc }}  # Encode the token using base64
